Repository inplayer-org/inplayer.js, pull requests merged in 2019-06, with the labels that each got.

#124 Update npm dependencies and fix falling tests
  CHANGELOG.md
  docs/classes/Account.html
  docs/classes/Asset.html
  docs/classes/Branding.html
  docs/classes/DLC.html
  docs/classes/InPlayer.html
  docs/classes/Payment.html
  docs/classes/Subscription.html
  docs/classes/Voucher.html
  docs/data.json
  docs/files/src_Models_Account.js.html
  docs/files/src_Models_Asset.js.html
  docs/files/src_Models_Branding.js.html
  docs/files/src_Models_Dlc.js.html
  docs/files/src_Models_Payment.js.html
  docs/files/src_Models_Subscription.js.html
  docs/files/src_Models_Voucher.js.html
  docs/files/src_index.js.html
  docs/index.html
  package.json
  src/Models/Account.js
  test/Account.test.js
  test/Asset.test.js
  test/Payment.test.js
  test/Subscription.test.js
  test/Voucher.test.js
  yuidoc.json
Labels: dependencies, security

#137 Update docs, rename endpoints in API config
  CHANGELOG.md
  docs/classes/Account.html
  docs/classes/Asset.html
  docs/classes/Branding.html
  docs/classes/DLC.html
  docs/classes/InPlayer.html
  docs/classes/Payment.html
  docs/classes/Subscription.html
  docs/classes/Voucher.html
  docs/data.json
  docs/files/src_Models_Account.js.html
  docs/files/src_Models_Asset.js.html
  docs/files/src_Models_Branding.js.html
  docs/files/src_Models_Dlc.js.html
  docs/files/src_Models_Payment.js.html
  docs/files/src_Models_Subscription.js.html
  docs/files/src_Models_Voucher.js.html
  docs/files/src_index.js.html
  docs/index.html
  package.json
  src/Models/Account.js
  src/Models/Asset.js
  src/Models/Payment.js
  src/Models/Subscription.js
  src/constants/endpoints.js
  yuidoc.json
Labels: enhancement

#140 543/feature/edit card details
  CHANGELOG.md
  src/Models/Payment.js
  src/constants/endpoints.js
Labels: feature

#141 v2.7.0
  CHANGELOG.md
  docs/classes/Account.html
  docs/classes/Asset.html
  docs/classes/Branding.html
  docs/classes/DLC.html
  docs/classes/InPlayer.html
  docs/classes/Payment.html
  docs/classes/Subscription.html
  docs/classes/Voucher.html
  docs/data.json
  docs/files/src_Models_Account.js.html
  docs/files/src_Models_Asset.js.html
  docs/files/src_Models_Branding.js.html
  docs/files/src_Models_Dlc.js.html
  docs/files/src_Models_Payment.js.html
  docs/files/src_Models_Subscription.js.html
  docs/files/src_Models_Voucher.js.html
  docs/files/src_index.js.html
  docs/index.html
  package.json
  src/Models/Payment.js
  src/constants/endpoints.js
  yarn.lock
  yuidoc.json
Labels: feature

#143 [2.7.1] - 27-06-2019
  CHANGELOG.md
  docs/classes/Account.html
  docs/classes/Asset.html
  docs/classes/Branding.html
  docs/classes/DLC.html
  docs/classes/InPlayer.html
  docs/classes/Payment.html
  docs/classes/Subscription.html
  docs/classes/Voucher.html
  docs/data.json
  docs/files/src_Models_Account.js.html
  docs/files/src_Models_Asset.js.html
  docs/files/src_Models_Branding.js.html
  docs/files/src_Models_Dlc.js.html
  docs/files/src_Models_Payment.js.html
  docs/files/src_Models_Subscription.js.html
  docs/files/src_Models_Voucher.js.html
  docs/files/src_index.js.html
  docs/index.html
  package.json
  src/Models/Payment.js
  yuidoc.json
Labels: enhancement
